
name: connectedCheck
on:
  push:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Configure JDK
      uses: actions/setup-java@v2.1.0
      with:
        distribution: adopt
        java-version: 16

    - name: Cache Gradle Dirs
      uses: actions/cache@v2.1.6
      with:
        path: |
          ~/.gradle/caches/
          ~/.gradle/wrapper/
        key: cache-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
        restore-keys: cache-gradle-

    - name: Run Tests
      uses: reactivecircus/android-emulator-runner@v2.18.0
      with:
        api-level: 29
        emulator-build: 6110076
        script: ./gradlew connectedCheck --stacktrace
      env:
        API_LEVEL: 29

    - name: Stop Gradle
      run: ./gradlew --stop
  
    
